---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.Common.ConfigMapName | default "cluster-config" }}
  namespace: {{ .Values.Common.namespace | default "k3fs" }}
data:
  ConfigMapStatus: "READY"
  ConfigMapName: {{ .Values.Common.ConfigMapName | quote }}
  NameSpace: {{ .Values.Common.namespace | quote }}
  NetworkType: {{ .Values.RdmaConfig.NetworkType | quote }}
  NetworkCard: {{ .Values.RdmaConfig.NetworkCard | quote }}

  # cluster
  FdbCluster: {{ .Values.Cluster.FdbCluster | quote }}
  ClusterId: {{ .Values.Cluster.ClusterId | quote }}
  MgmtdNodeNum: {{ .Values.Mgmtd.replicas | default .Values.Common.replicas | quote }}
  MetaNodeNum: {{ .Values.Meta.replicas | default .Values.Common.replicas | quote }}

  {{- if eq .Values.Storage.DeployMode "default" }}
  StorageNodeNum: {{ .Values.Storage.replicas | default .Values.Common.replicas | quote }}
  DiskPerNode: {{ .Values.Cluster.DiskPerNode | int | quote }}
  {{- else }}
  StorageNodeNum: {{ len .Values.Storage.NodeAllocation | quote }}
  {{- $Node := index .Values.Storage.NodeAllocation 0 }}
  {{- $diskCount := len (regexFindAll `"([^"]+)"` $Node.disk -1) }}
  DiskPerNode: {{ $diskCount | quote }}
  {{- end }}

  ChainTableId: {{ .Values.Cluster.ChainTableId | int | quote }}
  ChunkSize: {{ .Values.Cluster.ChunkSize | int | quote }}
  StripSize: {{ .Values.Cluster.StripSize | int | quote }}
  ReplicationFactor: {{ .Values.Cluster.ReplicationFactor | int | quote }}

  TargetIdPrefix: {{ .Values.Cluster.TargetIdPrefix | int | quote }} 
  ChainIdPrefix: {{ .Values.Cluster.ChainIdPrefix | int | quote }}
  NodeIdBegin: {{ .Values.Storage.IdStart | int | quote }}

  # monitor
  DBType: {{ .Values.Monitor.DBType | quote }}
  ClickhouseHost: {{ .Values.Monitor.ClickhouseHost | quote }}
  ClickhousePort: {{ .Values.Monitor.ClickhousePort | quote }}
  ClickhouseUser: {{ .Values.Monitor.ClickhouseUser | quote }}
  ClickhousePasswd: {{ .Values.Monitor.ClickhousePasswd | quote }}
  ClickhouseDB: {{ .Values.Monitor.ClickhouseDB | quote }}
  MonitorPort: {{ .Values.Monitor.Port | default 10000 | quote }}

  # mgmtd
  MgmtdRdmaPort: {{ .Values.Mgmtd.RdmaPort | default 8000 | quote }}
  MgmtdTcpPort: {{ .Values.Mgmtd.TcpPort | default 9000 | quote }}

  # meta
  MetaRdmaPort: {{ .Values.Meta.RdmaPort | default 8001 | quote }}
  MetaTcpPort: {{ .Values.Meta.TcpPort | default 9001 | quote }}

  # storage
  DeployMode: {{ .Values.Storage.DeployMode | quote }}
  StorageType: {{ .Values.Storage.StorageType | quote }}
  {{- if eq .Values.Storage.DeployMode "default" }}
  StorageRdmaPort: {{ .Values.Storage.RdmaPort | default 18001 | quote }}
  StorageTcpPort: {{ .Values.Storage.TcpPort | default 19001 | quote }}
  {{- end }}
  {{- if eq .Values.Storage.DeployMode "custom" }}
  ClearDisk: {{ .Values.Storage.ClearDisk | quote }}
  DiskIdType: {{ .Values.Storage.DiskIdType | quote }}
  {{- end }}

  # FuseClient
  MountPoint: {{ .Values.FuseClient.MountPoint | quote }}

