---
kind: ConfigMap
apiVersion: v1
metadata:
  name: rdma-config
  namespace: {{ .Values.Common.namespace | default "k3fs"  }}
data:
  rdma-config.sh: |-
    #!/bin/bash
    
    get_rdma_module() {
        for ((i=1; i<=60; i++)); do
            result=$(lsmod | grep ${Module})
            if [ -n "$result" ]; then
                echo "$NODE_HOSTNAME : ${Module} module has been loaded！"
                echo $result
                break
            else
                echo "$NODE_HOSTNAME : ${Module} module not load！"
                modprobe ${Module}
                if [ $? -ne 0 ]; then
                    echo "Can't load ${Module} module, exit."
                    exit 1
                fi
                sleep 10
            fi
        done
    }
    
    get_rdma_link(){
        for ((i=1; i<=60; i++)); do
            result=$(rdma link show | grep ${NetworkCard})
            if [ -n "$result" ]; then
                echo "$NODE_HOSTNAME rdma link is ready！"
                echo $result
                break
            else
                echo "$NODE_HOSTNAME rdma link is not ready！"
    
                rdma_link_result=$(rdma link add "rxe_${NetworkCard}" type rxe netdev "${NetworkCard}" 2>&1)
                exit_code=$?
    
                if [ -z "$rdma_link_result" ] && [ $exit_code -eq 0 ]; then
                    echo "$NODE_HOSTNAME : rdma link create success !"
                elif [ -n "$rdma_link_result" ] || [ $exit_code -ne 0 ]; then
                    echo "$NODE_HOSTNAME : rdma link create failed !"
                    [ -n "$rdma_link_result" ] && echo "Error Details: $rdma_link_result"
                fi
            fi
        done
    }

    if [ -z "${NetworkCard}" ]; then
        echo "NetworkCard parameter is null value, Please sset it."
        exit 1
    elif [ -d "/sys/class/net/${NetworkCard}" ]; then
        if [[ "$NetworkType" == "rdma" || "$NetworkType" == "rxe" ]]; then
            echo "NetworkType: ${NetworkType} , NetworkCard: ${NetworkCard} "
            if [[ "$NetworkType" == "rdma" ]]; then
                Module=rdma_cm
                rmmod rdma_rxe
            else
                Module=rdma_rxe
                rmmod rdma_cm
            fi
            get_rdma_module
            get_rdma_link
        else
            echo "NetworkType invalid value, Please use 'rdma' or 'rxe'."
            exit 1
        fi
    else
      echo "NetworkCard: ${NetworkCard} does not exist."
      exit 1
    fi








